### ISSUE TITLE
Gazeboでのnavigationパッケージのlaunchファイルについて

### ISSUE THREAD

**Issue by mantues** [vstoneofficial/lightrover_description#1]
このページにあるnavigationのチュートリアルですがGazeboを使用している場合のlaunchファイルを追記していただけないでしょうか。
https://vstoneofficial.github.io/lightrover_webdoc/software/navigation/

navigationの実行→launchファイルの呼び出し
roslaunch lightrover_ros lightrover_move_base_dwa.launch
ですが
Gazeboを使用している場合は下記になります。
roslaunch lightrover_description lightrover_move_base_dwa.launch

お忙しいところすみませんがよろしくお願いします。

**Comment by matsuyama-v** [comment]
記述を追加させて頂きました。
ご指摘ありがとうございます。
